AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Resources:
  ThePlayer007MediaConvertSource:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: "theplayer007-mediaconvert-source"

  ThePlayer007MediaConvertDestination:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: "theplayer007-mediaconvert-destination"

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: MediaconvertRecords
      AttributeDefinitions:
        - AttributeName: RecordId
          AttributeType: S
        - AttributeName: Timestamp
          AttributeType: N
      KeySchema:
        - AttributeName: RecordId
          KeyType: HASH
        - AttributeName: Timestamp
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 20
        WriteCapacityUnits: 20

  MediaConvertSnsTopic:
    Type: "AWS::SNS::Topic"
    Properties:
      TopicName: "mediaconvert-sns-topic"

  MediaConvertSnsSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: "mohitfury1997@gmail.com"
      Protocol: "email"
      TopicArn: !Ref MediaConvertSnsTopic

  MediaConvertSNSTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - Ref: MediaConvertSnsTopic
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sns:Publish
            Resource: !Ref MediaConvertSnsTopic

  MediaConvertEventBridgeEvent:
    Type: AWS::Events::Rule
    Properties:
      Description: "It monitors the media convert job state change event"
      EventPattern: 
        source:
          - "aws.mediaconvert"
        detail-type: 
          - "MediaConvert Job State Change"
        
      Name: "mediaconvert-job-state-change-rule"
      Targets:
        - Arn: !Ref MediaConvertSnsTopic
          Id: "MediaConvertJobStateChange"
    
  MediaConvertLambdaExecutionRole:  
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: "lambda.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "LambdaCloudwatchPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "arn:aws:logs:*:*:*"

        - PolicyName: "LambdaMediaConvertPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                 - "mediaconvert:*"
                 - "s3:ListAllMyBuckets"
                 - "s3:ListBucket"
                Resource: "*"

        - PolicyName: "PassRole"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "iam:PassRole"
                Resource: "*"
                Condition:
                  StringLike:
                    iam:PassedToService:
                      - "mediaconvert.amazonaws.com"

  MediaConvertS3Role:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: "mediaconvert.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "MediaConvertS3Policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "s3:*"
                  - "s3-object-lambda:*"
                Resource: "*"

  MediaConvertFunction:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: "lambda_function.lambda_handler"
      Runtime: "python3.10"
      CodeUri: "../terraform/lambda_function.zip"
      Role: !GetAtt MediaConvertLambdaExecutionRole.Arn
      Environment:
        Variables:
          DestinationBucket: !Ref ThePlayer007MediaConvertDestination
          MediaConvertRole: !GetAtt MediaConvertS3Role.Arn
      Events:
        S3Event:
          Type: "S3"
          Properties:
            Bucket: !Ref ThePlayer007MediaConvertSource
            Events: "s3:ObjectCreated:*"

  MediaConvertCloudfrontOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig: 
        Description: "mediaconvert-s3-oac"
        Name: "mediaconvert-s3-oac"
        OriginAccessControlOriginType: "s3"
        SigningBehavior: "always"
        SigningProtocol: "sigv4"

  MediaConvertCloudfrontDistribution:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        Enabled: true
        Origins:
          - Id: "theplayer007-mediaconvert-destination-origin"
            DomainName: "theplayer007-mediaconvert-destination.s3.us-east-1.amazonaws.com"
            S3OriginConfig: 
              OriginAccessIdentity: ""
            OriginAccessControlId: !GetAtt MediaConvertCloudfrontOriginAccessControl.Id
            ConnectionAttempts: 3
            ConnectionTimeout: 10
        DefaultCacheBehavior:
          Compress: true
          SmoothStreaming: false
          TargetOriginId: "theplayer007-mediaconvert-destination-origin"
          ViewerProtocolPolicy: "redirect-to-https"
          AllowedMethods: ["HEAD","GET"]
          CachedMethods: ["HEAD","GET"]
          DefaultTTL: 0
          MinTTL: 0
          MaxTTL: 0
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: "all"
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
        DefaultRootObject: "index.html"
        IPV6Enabled : false
        PriceClass: "PriceClass_200"
  
  MediaConvertDestinationBucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref ThePlayer007MediaConvertDestination
      PolicyDocument:
        Version: "2012-10-17"
        Id: "PolicyForCloudFrontPrivateContent"
        Statement:
          - Sid: "AllowCloudFrontServicePrincipal"
            Effect: "Allow"
            Principal:
              Service: "cloudfront.amazonaws.com"
            Action: "s3:GetObject"
            Resource: !Sub "${ThePlayer007MediaConvertDestination.Arn}/*"
            Condition:
              StringEquals:
                AWS:SourceArn: !GetAtt MediaConvertCloudfrontDistribution.Arn

# Outputs:
#   LambdaFunctionArn:
#     Value: !GetAtt MyLambdaFunction.Arn
#   S3BucketName:
#     Value: !Ref MyS3Bucket
